server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  application:
    name: Payment-Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
  instance:
    hostname: localhost
logging:
  file: /Users/rafik/projects/java/springboot/customer/log/customer.log